[tool.uv.workspace]
members = [
    "py-lib",
    "reg23",
]

# these define which sources to install some particular packages from
[tool.uv.sources]
# reg23 is installed from the current workspace
reg23 = { workspace = true }